export const ROLES = {
  ADMIN: "Admin",
  STAFF: "Staff",
  VIEWER: "Viewer",
} as const;

export const ACTIONS = {
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
} as const;

export const TYPE_STOCK_TRANSECTION = {
  IN: "IN",
  OUT: "OUT",
  ADJUST: "ADJUST"
}

export const STATUS_PO = {
  DRAFT: "Draft",
  CONFIRMED: "Confirmed",
  RECEIVED: "Received",
  CANCELLED: "Cancelled"
}